# Generated by Django 4.1.3 on 2024-10-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '00010_load_timatable_from_excel_v16'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswallet',
            name='trust_rate',
            field=models.FloatField(default=1),
        ),
    ]
