# Generated by Django 4.1.3 on 2024-11-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_update_timetable_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_time', models.TimeField(auto_now_add=True)),
                ('trust_rate', models.FloatField(default=1)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_booked_audience', to='main.audience')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_booked_users_wallet', to='main.userswallet')),
            ],
        ),
    ]
