# Generated by Django 4.1.3 on 2024-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=150)),
                ('owner_user_wallet', models.CharField(max_length=255)),
                ('order_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
