# Generated by Django 4.1.3 on 2024-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_usersearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='audience_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
