# Generated by Django 4.1.3 on 2024-10-27 15:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteGroupDayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_pairs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, max_length=8, null=True, size=None), blank=True, max_length=20, null=True, size=None), blank=True, max_length=7, null=True, size=None)),
                ('visibility', models.IntegerField(default=0)),
                ('institute_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_group', to='main.institutegroup')),
            ],
        ),
        migrations.AddField(
            model_name='institutegroup',
            name='institute_group_day_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituteGroupDayHistory', to='main.institutegroupdayhistory'),
        ),
    ]
