# Generated by Django 4.1.3 on 2024-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_load_timatable_from_excel_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_preferences', to='main.preferences'),
        ),
    ]
